Learn 274
betrybe/flake8-linter-action pull request #1
Opened 2020-09-24 13:03 UTC by eucleciojosias

[Issue LEARN-274](https://trybe.atlassian.net/browse/LEARN-274?atlOrigin=eyJpIjoiNGZhNDRhNWRiM2IyNDExMTlkNWM0NjZjOTg3ODFjYzYiLCJwIjoiaiJ9)

2020-09-25 13:49 UTC, eucleciojosias commented
<script src="https://gist.github.com/krnd/1f3fb6c05af365977e486c47cb7b4a72.js"></script>

2020-09-25 13:51 UTC, eucleciojosias commented
{% gist 1f3fb6c05af365977e486c47cb7b4a72 %}

2020-09-25 14:56 UTC, jeanpsv requested changes

2020-09-25 14:56 UTC, jeanpsv commented on README.md
> +GitHub main branch to get the original tests and requirements.s
O passo de _linter_ não faz o clone dos arquivos originais. Como geralmente são arquivos de testes não é necessário adicionar essa função aqui.

Vamos ajustar a integridade de forma definitiva agora no Q4

2020-09-25 14:56 UTC, jeanpsv commented on action.yml
> +  image: 'Dockerfile'
Acredito que é necessário passar os `inputs` para a imagem Docker

2020-09-25 19:05 UTC, eucleciojosias commented on action.yml
> +  image: 'Dockerfile'
O Github Actions transforma cada _input_ definida no arquivo `action.yml` em uma _envvar_ com o prefixo `INPUT_{INPUT_NAME}` conforme é visível [aqui](https://github.com/tryber/tech-news-test/pull/1/checks?check_run_id=1166253511#step:6:6), dessa forma não preciso passar como argumento.

2020-09-25 19:07 UTC, eucleciojosias commented on README.md
> +GitHub main branch to get the original tests and requirements.s
Removido

2020-09-25 20:20 UTC, jeanpsv approved these changes

2020-09-25 20:37 UTC, eucleciojosias commented on README.md
> +This example was get from the this [Gist](https://gist.github.com/krnd/1f3fb6c05af365977e486c47cb7b4a72#file-flake8).
```suggestion
This example was get from this [Gist](https://gist.github.com/krnd/1f3fb6c05af365977e486c47cb7b4a72#file-flake8).
```

2020-09-29 12:35 UTC, LeandroLM requested changes

2020-09-29 12:35 UTC, LeandroLM commented on README.md
> +This action run Flake8 over a project and comment on PR the errors found.
```suggestion
This action runs Flake8 over a project and comments on PR the errors found.
```

2020-09-29 12:35 UTC, LeandroLM commented on README.md
> +
```suggestion
```

2020-09-29 12:35 UTC, LeandroLM commented on README.md
> +Pull Request number that trigger build.
```suggestion
Pull Request number that triggered the build.
```

2020-09-29 12:35 UTC, LeandroLM commented on README.md
> +In order to configure the ESLint analysis for your project, you must create or modify the `setup.cfg` file at the root of your project.
Aqui seria Flake8 né?

```suggestion
In order to configure the Flake8 analysis for your project, you must create or modify the `setup.cfg` file at the root of your project.
```

2020-09-29 12:35 UTC, LeandroLM commented on action.yml
> +description: 'Run Flake8 over a project and comment on the student PR the errors found.'
```suggestion
description: 'Runs Flake8 over a project and comments on the student PR the errors found.'
```

2020-09-29 12:35 UTC, LeandroLM commented on src/main.py
> +        msg = 'Foi encontrado {} erro'.format(feedback['count'])
Já não podia fazer asim de uma vez?

```suggestion
        msg = 'Foi encontrado 1 erro'
```

2020-09-29 12:35 UTC, LeandroLM commented on src/main.py
> +        raise ValueError('You must pass report and requirements files as argument!')
```suggestion
        raise ValueError('You must pass report and requirements files as arguments!')
```

2020-09-29 14:17 UTC, LeandroLM requested changes

2020-09-29 14:17 UTC, LeandroLM commented on README.md
> +Pull Request number triggered the build.
```suggestion
Pull Request number that triggered the build.
```

2020-09-29 16:22 UTC, LeandroLM approved these changes

2020-09-30 16:19 UTC, merged