imp: Usa imagem do python
betrybe/flake8-linter-action pull request #3
Opened 2020-11-19 20:07 UTC by eucleciojosias

2020-11-20 12:05 UTC, jeanpsv approved these changes

2020-11-20 17:21 UTC, inaC commented on Dockerfile
> +FROM python:3.9.0-buster
Era para usar essa versão do python mesmo? No conteúdo as pessoas estudantes são [instruídas](https://app.betrybe.com/course/computer-science/python/intro/conteudos/terminal-interativo-repl?use_case=side_bar) a instalarem a versão `3.8.2`

2020-11-20 17:21 UTC, inaC commented on entrypoint.sh
> +  python3 -m pip install -r dev-requirements.txt
Para que que serve o arquivo`dev-requirements.txt`? Um projeto pode ter 2 arquivos de mapeamentos de requisito?

2020-11-20 17:25 UTC, eucleciojosias commented on entrypoint.sh
> +  python3 -m pip install -r dev-requirements.txt
Seria como as chaves `devDependencies` e `dependencies` do `package.json` de um projeto JS. No caso, as dependências só para ambiente dev são no `dev-requirements.txt`, como o código do aluno sempre vai rodar os testes, vamos instalar sempre as dependências dev.

2020-11-20 17:26 UTC, eucleciojosias commented on Dockerfile
> +FROM python:3.9.0-buster
Boa dúvida, vou checar com o Batista ou Cássio, mas creio que seria problema se fosse uma versão anterior à `3.8.2`

2020-11-20 19:01 UTC, eucleciojosias commented on Dockerfile
> +FROM python:3.9.0-buster
@inaC  conversei com o @brunobatista25 ele falou que não dá problemas

2020-11-23 14:32 UTC, inaC requested changes
O CI [não está passando na etapa de lint](https://github.com/betrybe/flake8-linter-action/pull/3/checks?check_run_id=1433455727#step:5:11)

2020-11-23 14:32 UTC, inaC commented on tests/fixture/expected_comment.md
> +### Foram encontrados 2 avisos.
O formato da mensagem de feedback está num formato diferente do formato das mensagens de feedback das actions do estlint e do stylelint 🤔 

Nas actions do eslint e do stylelint, os erros são separados dos avisos, e a mensagem de feedback teria o seguinte formato, para esta fixture:

```md
### Foram encontrados 6 erros.

#### Arquivo `./python/scripts/githubsearch.py`

- Linha **4**: F401 'json' imported but unused
- Linha **12**: E302 expected 2 blank lines, found 1
- Linha **145**: E501 line too long (88 > 79 characters)
- Linha **161**: E303 too many blank lines (2)

#### Arquivo `./python/scripts/main.py`

- Linha **33**: E711 comparison to None should be 'if cond is None:'
- Linha **40**: F841 local variable 'datetime_object' is assigned to but never used

### Foram encontrados 2 avisos.

#### Arquivo `./python/scripts/main.py`

- Linha **48**: W292 no newline at end of file
- Linha **52**: W291 trailing whitespace
```

2020-11-23 14:46 UTC, LeandroLM approved these changes

2020-11-23 15:10 UTC, eucleciojosias commented on tests/fixture/expected_comment.md
> +### Foram encontrados 2 avisos.
@inaC sim, isso falta eu enviar ainda

2020-11-23 15:34 UTC, eucleciojosias commented on tests/fixture/expected_comment.md
> +### Foram encontrados 2 avisos.
Finalizado os ajustes agora

2020-11-23 19:03 UTC, inaC approved these changes

2020-11-23 20:23 UTC, merged